query Contacts {
  contacts {
    edges {
      node {
        id
        name
        email
        company
        phone
        address1
        address2
        city
        province
        provinceCode
        zip
        country
        countryCode
        creditLimit
        openBalance
        availableCredit
        quickBookCustomerId
        active
      }
    }
  }
}
