query Invoices {
    invoices {
        edges {
            node {
                id
                invoiceStatus
                invoiceNumber
                customer {
                    name
                }
                date
                shipmentID
            }
        }
    }
}