query Receipts {
    receipts {
        edges {
            node {
                id
                receiptStatus
                receiptNumber
                supplier {
                    name
                }
                purchaseOrder {
                    id
                }
                date
            }
        }
    }
}