query StockSummaries {
  stockSummaries {
    edges {
      node {
        id
        variantID
        averageCost
        inStockQuantity
        onHoldQuantity
        availableQuantity
        totalCost
        variant {
          product {
            handle
          }
        }
      }
    }
  }
}
