query SalesOrderLineItems($salesOrderID: ID!) {
  salesOrderLineItems(query: { salesOrderID: { eq: $salesOrderID } }) {
    edges {
      cursor
      node {
        quantity
        created
        createdByID
        createdAt
        salesOrderID
        updatedAt
        variantID
        shopifyID
        name
        taxable
        fulfillmentStatus
        active
        updated
        discount
        sku
        requiresShipping
        unitPrice
        subtotalPrice
        updatedByID
        unitCompareAtPrice
        id
        variant {
          sku
          inventoryItemID
          updated
          createdAt
          updatedAt
          created
          shopifyID
          inventoryQuantity
          updatedByID
          quickbookItemName
          createdByID
          availableForSale
          price
          inventoryType
          imageID
          displayName
          productID
          active
          taxable
          id
          quickbookItemId
          quickbookSyncToken
          barcode
          inventoryItem {
            shopifyID
            updated
            updatedByID
            updatedAt
            active
            productVariantID
            createdAt
            created
            id
            createdByID
            productVariant {
              sku
              inventoryItemID
              updated
              createdAt
              updatedAt
              created
              shopifyID
              inventoryQuantity
              updatedByID
              quickbookItemName
              createdByID
              availableForSale
              price
              inventoryType
              imageID
              displayName
              productID
              active
              taxable
              id
              quickbookItemId
              quickbookSyncToken
              barcode
              image {
                id
                updatedAt
                altText
                createdByID
                shopifyID
                createdAt
                updated
                active
                created
                updatedByID
                url
              }
            }
          }
        }
      }
    }
  }
}
