query BillOfMaterial ($id: ID!) {
    bom(id: $id) {
        id
        name
        sku
        description
        bomType
        item {
            name
        }
        outputQuantity
        uom {
            name
        }
    }
}