query MyQuery($operationId:ID!) {
  operationDependencies(query: {operationId: {eq: $operationId}}) {
    collection {
      id
      dependsOnOperation {
        name
        order
        duration
        documentUrl
        description
        id
      }
    }
  }
}