query MyQuery {
  mOBatches(query: {isDeleted: {eq: false}}) {
    collection {
      id
     
      name
      quantity
      status
      startDateTime
      endDateTime
      
      bom{
        name
      }
      batchSize
    }
  }
}
