query ($id: [ID]!) {
  workOrders(query: { id: { in: $id } }) {
    collection {
      id
      endDate
      realDuration
      operationId
      operation {
        name
        workCenter{
          name
        }
      }
      status
      startDate
      endDate
      expectedDuration
      moId
      mo {
        name
      }
    }
  }
}
