query {
  items(
    size: 1000,
    order: { field: createdAt, direction: Desc }
    query: {isActive: {eq: true}}
  ) {
    collection {
      id
      name
      uom {
        name
      }
      uomId
      isFinalProduct
      inventoryType
    }
  }
}
