query ($bomId: ID!, $outputQuantity: Float!) {
  simulateInputRequirementByOutputQuantity(
    input: { bomId: $bomId, outputQuantity: $outputQuantity }
  ) {
    result {
      uomId
      outputQuantity
      itemId
    }
  }
}
