query {
  uoms(
       size: 1000,
       order: { field: createdAt, direction: Asc }
       query: {isActive: {eq: true}}
  ) {
    collection {
      id
      name
      isActive
      description
    }
  }
}
