cue:
  package: tailor.build/scm-pxxmksnj
gateway:
  domain: "scm-pxxmksnj.erp.dev"
  graphqlEndpoint: "https://scm-pxxmksnj.erp.dev/query"
tailordb:
  namespace: "scm-pxxmksnj"
  graphqlEndpoint: "https://tailordb/graphql/scm-pxxmksnj"
stateflow:
  namespace: "scm-pxxmksnj"
  graphqlEndpoint: "https://stateflow/graphql/scm-pxxmksnj"
directory:
  graphqlEndpoint: "https://directory/graph"
pipeline:
  namespace: "scm-pxxmksnj"
  graphqlEndpoint: "https://pipeline/graphql/scm-pxxmksnj"
